// Generated by draad-codegen. Do not edit.

/** Totals, not rates: a smoothed rate is dominated by bursts. */
export type StatsDto = { frames: number, presents: number, dropped: number, };

/** The document, flattened for the canvas. Sent per edit, not per frame. */
export type TimelineDto = { tracks: TrackDto[], length: number, };

export type TrackDto = { clips: ClipDto[], };

export type ClipDto = { id: number, position: number, length: number, source_start: number, source_length: number, name: string, };

export type TransportDto = { playhead: number, playing: boolean, fps: number, };

export class SurfaceApi {
	constructor(private rpc: Rpc) {}

	/**
	 * Where the page has left room for the video, in physical pixels,
	 * along with its own viewport so the two coordinate spaces can be
	 * checked against each other.
	 */
	setRect(x: number, y: number, width: number, height: number, page_width: number, page_height: number): Promise<void> {
		return this.rpc.call("surface/set_rect", { x, y, width, height, page_width, page_height });
	}

	/**
	 * What to clear the surface to, so the area around the letterboxed
	 * video matches the chrome.
	 */
	setChrome(r: number, g: number, b: number): Promise<void> {
		return this.rpc.call("surface/set_chrome", { r, g, b });
	}

	/** Frame counters, for the readout. */
	stats(): Promise<StatsDto> {
		return this.rpc.call("surface/stats");
	}
}

export class TimelineApi {
	constructor(private rpc: Rpc) {}

	/** The document as it currently stands, or nothing before one opens. */
	get(): Promise<TimelineDto | null> {
		return this.rpc.call("timeline/get");
	}
}

export class TransportApi {
	constructor(private rpc: Rpc) {}

	/** Where the playhead is, and whether it is moving. */
	state(): Promise<TransportDto> {
		return this.rpc.call("transport/state");
	}

	/** Move the playhead to `frame`. */
	seek(frame: number): Promise<void> {
		return this.rpc.call("transport/seek", { frame });
	}

	/** Start or stop playback. */
	toggle(): Promise<void> {
		return this.rpc.call("transport/toggle");
	}
}

/** Pushed when the document changes, so the canvas never has to poll for it. */
export class TimelineEvents {
	constructor(private rpc: Rpc) {}

	onChanged(handler: (payload: TimelineDto) => void): UnlistenFn {
		return this.rpc.listen<TimelineDto>("timeline/changed", handler);
	}
}

export class TransportEvents {
	constructor(private rpc: Rpc) {}

	onChanged(handler: (payload: TransportDto) => void): UnlistenFn {
		return this.rpc.listen<TransportDto>("transport/changed", handler);
	}
}

export class Api {
	surface: SurfaceApi;
	timeline: TimelineApi;
	transport: TransportApi;
	/** Pushed when the document changes, so the canvas never has to poll for it. */
	timelineEvents: TimelineEvents;
	transportEvents: TransportEvents;

	constructor(private rpc: Rpc) {
		this.surface = new SurfaceApi(rpc);
		this.timeline = new TimelineApi(rpc);
		this.transport = new TransportApi(rpc);
		this.timelineEvents = new TimelineEvents(rpc);
		this.transportEvents = new TransportEvents(rpc);
	}

	/**
	 * Subscribe to every failed RPC call from this `Api`.
	 * The handler fires *before* the promise rejects, so local
	 * `try { ... } catch (e)` blocks still see the error too.
	 * Returns an unsubscribe handle, or a no-op if the underlying
	 * transport does not implement `onError`.
	 */
	onError(handler: (err: RpcError) => void): UnlistenFn {
		return this.rpc.onError?.(handler) ?? (() => {});
	}
}

/** Returned by `Rpc.listen`, call to unsubscribe. */
export type UnlistenFn = () => void;

/** HTTP verb a generated method maps to. */
export type HttpVerb = "GET" | "POST" | "PUT" | "PATCH" | "DELETE";

/**
 * Transport contract the generated API classes call into. Implement this
 * in your app (using fetch / axios / tauri / etc.) and pass it to
 * `new Api(rpc)`. Or use `defaultRpc(...)` below.
 */
export interface Rpc {
	/**
	 * Send an RPC request. The wire command is `{namespace}/{method}`.
	 * Verb defaults to POST (body-bearing); GET/DELETE callers must pass
	 * the verb explicitly so `args` is serialised as a query string.
	 */
	call<T>(command: string, args?: Record<string, unknown>, method?: HttpVerb): Promise<T>;

	/** Subscribe to a backend event. Returns an unsubscribe handle. */
	listen<T>(topic: string, handler: (payload: T) => void): UnlistenFn;

	/**
	 * Run `handler` every time the event socket (re)connects, *after* live
	 * subscriptions have been restored. Use it to re-establish per-session
	 * state on the server (e.g. re-announce presence). Optional on the
	 * interface — custom transports can omit it.
	 */
	onOpen?(handler: () => void): UnlistenFn;

	/**
	 * Send a raw application frame to the server over the event socket —
	 * e.g. a presence announce or a client→client publish. The shape is
	 * app-defined; draad reserves only `{type:"subscribe"|"unsubscribe"}`.
	 * Connects the socket on demand and buffers until it's open. Optional
	 * on the interface.
	 */
	send?(frame: Record<string, unknown>): void;

	/**
	 * Subscribe to every failed RPC call. The handler fires *before* the
	 * promise rejects, so local `try { ... } catch (e)` paths still see
	 * the error too. Useful for global concerns: toast on error, route
	 * 401s to a sign-in flow, ship a Sentry breadcrumb, etc. Optional on
	 * the interface — custom transports can omit it.
	 */
	onError?(handler: (err: RpcError) => void): UnlistenFn;
}

/**
 * Thrown (or returned) by `Rpc.call` implementations on failure.
 *
 * The generic `E` is the shape of the server's error body — generated
 * methods tag their `@throws` with the concrete error type pulled from
 * the trait's `Result<_, E>` return.
 */
export class RpcError<E = unknown> extends Error {
	constructor(
		public readonly code: string,
		/** HTTP status code from the response (or 0 if the request never reached the server). */
		public readonly status: number,
		/**
		 * Parsed JSON body from the server, when present. Falls back to
		 * the raw response text on non-JSON responses, and to `null`
		 * when the body was empty.
		 */
		public readonly body: E | string | null,
		message: string,
	) {
		super(message);
		this.name = "RpcError";
	}
}

/**
 * A connected client: the unified transport handle returned by
 * {@link defaultRpc}. `call` rides HTTP; `listen` / `send` / events ride the
 * WebSocket channel. Carries the server-assigned {@link Conn.id} that ties the
 * two together.
 */
export interface Conn extends Rpc {
	/**
	 * Server-assigned, reconnect-stable client id. `null` until the first
	 * `$draad/welcome` frame arrives after the initial connect; stable across
	 * reconnects thereafter. Sent as the `x-draad-client` header on every
	 * `call` and as `?resume=` on WebSocket reconnects.
	 */
	readonly id: string | null;
}

export type DefaultRpcOptions = {
	/** Base URL for RPC calls. Requests go to `${baseUrl}/${command}`. */
	baseUrl?: string;
	/** WebSocket URL for events. Omit to make `listen()` throw. */
	wsUrl?: string;
	/** Extra headers added to every RPC call. */
	headers?: Record<string, string>;
	/** Disable WebSocket auto-reconnect. Default: true. */
	reconnect?: boolean;
	/** Cap on the backoff between reconnect attempts. Default: 30000. */
	maxReconnectDelayMs?: number;
};

/**
 * Default `Rpc` implementation: POST JSON for calls, a shared WebSocket
 * for events. Wire format:
 *
 *  - Calls: `POST {baseUrl}/{command}` with body `args`. 2xx responses
 *    are parsed as JSON and returned; non-2xx are thrown as `RpcError`.
 *  - Events: WS frames shaped `{ topic: string, payload: T }`.
 *
 * Auto-reconnects with exponential backoff + jitter (capped at
 * `maxReconnectDelayMs`) as long as there are active subscribers. Replace
 * with your own `Rpc` for auth, custom transports, or a different wire
 * format.
 */
export function defaultRpc(opts: DefaultRpcOptions = {}): Conn {
	const baseUrl = opts.baseUrl ?? "/api";
	const maxDelayMs = opts.maxReconnectDelayMs ?? 30000;
	const shouldReconnect = opts.reconnect !== false;
	const subs = new Map<string, Set<(payload: unknown) => void>>();
	const errorHandlers = new Set<(err: RpcError) => void>();
	const openHandlers = new Set<() => void>();
	// Frames requested via `send()` before the socket was open; flushed on open.
	const pendingSends: string[] = [];
	let ws: WebSocket | undefined;
	let reconnectDelayMs = 500;
	let reconnectTimer: ReturnType<typeof setTimeout> | undefined;

	// Server-assigned identity, persisted so it survives reloads and is
	// replayed (HTTP header + WS `?resume=`) to tie calls to the socket.
	const CLIENT_KEY = "draad.client";
	let clientId: string | null = readStoredClientId();

	function readStoredClientId(): string | null {
		try {
			return typeof sessionStorage !== "undefined" ? sessionStorage.getItem(CLIENT_KEY) : null;
		} catch { return null; }
	}
	function setClientId(id: unknown): void {
		if (typeof id !== "string" || !id || id === clientId) return;
		clientId = id;
		try { sessionStorage.setItem(CLIENT_KEY, id); } catch { /* ignore */ }
	}

	function fireError(err: RpcError): RpcError {
		// Notify every observer; a single throwing handler must not
		// take out the others, hence the per-handler try/catch.
		for (const h of errorHandlers) {
			try { h(err); } catch { /* swallow handler errors */ }
		}
		return err;
	}

	function flushPending(): void {
		if (!ws || ws.readyState !== WebSocket.OPEN) return;
		for (const frame of pendingSends.splice(0)) ws.send(frame);
	}

	function rawSend(frame: Record<string, unknown>): void {
		ensureWs();
		pendingSends.push(JSON.stringify(frame));
		flushPending();
	}

	function resumeUrl(): string {
		const base = opts.wsUrl!;
		if (!clientId) return base;
		return base + (base.includes("?") ? "&" : "?") + "resume=" + encodeURIComponent(clientId);
	}

	function openWs(): WebSocket {
		const sock = new WebSocket(resumeUrl());
		// Fire onOpen handlers exactly once per socket. On a fresh connect we
		// wait for the `$draad/welcome` frame first so handlers can read
		// `conn.id`; on a resume the id is already known, so fire on open.
		let firedOpen = false;
		const fireOpen = () => {
			if (firedOpen) return;
			firedOpen = true;
			for (const h of openHandlers) {
				try { h(); } catch { /* swallow handler errors */ }
			}
		};
		sock.addEventListener("open", () => {
			reconnectDelayMs = 500;
			// Restore every live subscription, then flush queued sends.
			for (const topic of subs.keys()) sock.send(JSON.stringify({ type: "subscribe", topic }));
			flushPending();
			if (clientId) fireOpen();
		});
		sock.addEventListener("message", (ev) => {
			try {
				const { topic, payload } = JSON.parse(String(ev.data));
				// draad's control frame: learn (or confirm) our id, then —
				// on a fresh connect — release the deferred onOpen handlers.
				if (topic === "$draad/welcome") {
					setClientId(payload?.clientId);
					fireOpen();
					return;
				}
				subs.get(topic)?.forEach((h) => h(payload));
			} catch {
				/* ignore malformed frames */
			}
		});
		sock.addEventListener("close", () => {
			ws = undefined;
			if (!shouldReconnect || subs.size === 0) return;
			const base = Math.min(reconnectDelayMs, maxDelayMs);
			const jitter = base * (0.8 + Math.random() * 0.4);
			reconnectDelayMs = Math.min(reconnectDelayMs * 2, maxDelayMs);
			reconnectTimer = setTimeout(() => {
				reconnectTimer = undefined;
				if (subs.size > 0 && !ws) ws = openWs();
			}, jitter);
		});
		return sock;
	}

	function ensureWs(): WebSocket {
		if (!opts.wsUrl) {
			throw new RpcError("NO_WS_URL", 0, null, "defaultRpc: wsUrl not configured; cannot listen()");
		}
		if (ws && ws.readyState !== WebSocket.CLOSED) return ws;
		ws = openWs();
		return ws;
	}

	return {
		get id(): string | null {
			return clientId;
		},
		async call<T>(command: string, args?: Record<string, unknown>, method: HttpVerb = "POST"): Promise<T> {
			const hasBody = method === "POST" || method === "PUT" || method === "PATCH";
			let url = `${baseUrl}/${command}`;
			const headers: Record<string, string> = { ...opts.headers };
			// Replay our identity so the server can tie this call to our socket.
			if (clientId) headers["x-draad-client"] = clientId;
			const init: RequestInit = { method, headers };
			if (hasBody) {
				(init.headers as Record<string, string>)["Content-Type"] = "application/json";
				init.body = JSON.stringify(args ?? {});
			} else if (args) {
				const params = new URLSearchParams();
				for (const [k, v] of Object.entries(args)) {
					if (v === undefined || v === null) continue;
					if (Array.isArray(v)) {
						for (const item of v) params.append(k, String(item));
					} else {
						params.append(k, String(v));
					}
				}
				const qs = params.toString();
				if (qs) url += `?${qs}`;
			}
			// Every failure path constructs an `RpcError`, fires the
			// global `onError` observers, then throws — so callers'
			// local try/catch and global handlers both see it.
			let res: Response;
			try {
				res = await fetch(url, init);
			} catch (e) {
				const msg = e instanceof Error ? e.message : String(e);
				throw fireError(new RpcError("NETWORK", 0, null, msg));
			}
			if (!res.ok) {
				// Best effort at giving callers the typed body their
				// `@throws` jsdoc promised: read once as text, try
				// JSON.parse, fall back to the raw string. Empty body
				// becomes null so `instanceof` checks stay clean.
				const raw = await res.text();
				let body: unknown = null;
				if (raw.length > 0) {
					try {
						body = JSON.parse(raw);
					} catch {
						body = raw;
					}
				}
				const message = typeof body === "string" ? body : res.statusText;
				throw fireError(new RpcError(`HTTP_${res.status}`, res.status, body as never, message));
			}
			try {
				return (await res.json()) as T;
			} catch (e) {
				const msg = e instanceof Error ? e.message : String(e);
				throw fireError(new RpcError("BAD_BODY", res.status, null, msg));
			}
		},
		listen<T>(topic: string, handler: (payload: T) => void): UnlistenFn {
			const sock = ensureWs();
			let set = subs.get(topic);
			const isFirst = !set;
			if (!set) {
				set = new Set();
				subs.set(topic, set);
			}
			const wrapped = handler as (p: unknown) => void;
			set.add(wrapped);
			// First listener for this topic asks the server to start sending
			// it. On a not-yet-open socket the `open` handler resubscribes
			// everything, so only send now if it's already connected.
			if (isFirst && sock.readyState === WebSocket.OPEN) {
				sock.send(JSON.stringify({ type: "subscribe", topic }));
			}
			return () => {
				set!.delete(wrapped);
				if (set!.size === 0) {
					subs.delete(topic);
					// Last listener gone: stop the server sending this topic.
					if (ws && ws.readyState === WebSocket.OPEN) {
						ws.send(JSON.stringify({ type: "unsubscribe", topic }));
					}
				}
				if (subs.size === 0 && reconnectTimer) {
					clearTimeout(reconnectTimer);
					reconnectTimer = undefined;
				}
			};
		},
		onOpen(handler: () => void): UnlistenFn {
			openHandlers.add(handler);
			// Already connected? Fire immediately so callers don't miss the
			// current session.
			if (ws && ws.readyState === WebSocket.OPEN) handler();
			return () => { openHandlers.delete(handler); };
		},
		send(frame: Record<string, unknown>): void {
			rawSend(frame);
		},
		onError(handler: (err: RpcError) => void): UnlistenFn {
			errorHandlers.add(handler);
			return () => { errorHandlers.delete(handler); };
		},
	};
}

/**
 * Transport for a Tauri app: `call` goes over the webview's IPC bridge and
 * `listen` over its event system, so there is no socket and no port.
 *
 * The wire command `namespace/method` becomes the Tauri command
 * `namespace_method`, which is what the `tauri` feature's codegen emits.
 * Verbs are ignored — IPC has none.
 *
 * ```ts
 * const api = new Api(tauriRpc());
 * ```
 *
 * Pass the Tauri API explicitly if the globals are not injected — i.e. when
 * `withGlobalTauri` is off and you import `@tauri-apps/api` instead:
 *
 * ```ts
 * import { invoke } from "@tauri-apps/api/core";
 * import { listen } from "@tauri-apps/api/event";
 * const api = new Api(tauriRpc({ invoke, listen }));
 * ```
 */
export interface TauriBindings {
	invoke<T>(command: string, args?: Record<string, unknown>): Promise<T>;
	listen<T>(
		event: string,
		handler: (event: { payload: T }) => void,
	): Promise<() => void>;
}

export function tauriRpc(bindings?: TauriBindings): Rpc {
	const globals = (globalThis as Record<string, any>).__TAURI__;
	const tauri: TauriBindings | undefined =
		bindings ??
		(globals && { invoke: globals.core.invoke, listen: globals.event.listen });

	if (!tauri) {
		throw new Error(
			"draad: no Tauri bindings. Enable `withGlobalTauri` in tauri.conf.json, " +
				"or pass { invoke, listen } from @tauri-apps/api.",
		);
	}

	return {
		async call<T>(command: string, args?: Record<string, unknown>): Promise<T> {
			try {
				return await tauri.invoke<T>(command.replace("/", "_"), args ?? {});
			} catch (e) {
				// Commands reject with the `Err` side of the handler's
				// `Result`, already serialised. There is no status code
				// here, so 0 stands for "never reached a server".
				throw new RpcError(command, 0, e as never, String(e));
			}
		},

		listen<T>(topic: string, handler: (payload: T) => void): UnlistenFn {
			// Tauri hands back the unlisten through a promise; the Rpc
			// contract is synchronous, so unsubscribing before it resolves
			// has to be remembered rather than dropped.
			let stop: (() => void) | undefined;
			let cancelled = false;

			void tauri.listen<T>(topic, (event) => handler(event.payload)).then((off) => {
				if (cancelled) off();
				else stop = off;
			});

			return () => {
				cancelled = true;
				stop?.();
			};
		},
	};
}
